# Generated by Django 2.0.1 on 2018-01-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='door_count',
            new_name='doorCount',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='drive_train',
            new_name='driveTrain',
        ),
    ]
