# Generated by Django 2.0.1 on 2018-01-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('door_count', models.IntegerField()),
                ('drive_train', models.CharField(max_length=50)),
            ],
        ),
    ]
